name: Saludo usando variables y secrets
run-name: ¡Estoy aprendiendo a usar Secrets y variables!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo variables 
        run: echo "$SALUDO, ${{ vars.NOMBRE}}. Hoy es ${{ env.DIA_DE_SEMANA }}!"
  saludo-SECRETS:
      runs-on: ubuntu-latest
      steps:
        - name: Saludo secrets 
          run: echo "$SALUDO, ${{ vars.NOMBRE}}. tu conraseña es ${{ secrets.PASSWORD }}!"
